spring:
  application:
    name: spotify-analytics-tracker

  profiles:
    default: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  timezone: America/Guayaquil

logging:
  level:
    org.hibernate.SQL: debug
