spring:
  application:
    name: spotify-analytics-tracker

  profiles:
    default: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  timezone: America/Guayaquil
  tracker:
    interval-ms: 20000
  backup:
    interval-ms: 1800000
    initial-delay-ms: 60000

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: http://127.0.0.1:8080/api/spotify/callback

logging:
  level:
    com.danielcarvajal.spotifytracker: debug
